# Generated by Django 2.1.4 on 2020-03-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0004_department_employee_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
