# Generated by Django 2.1.4 on 2020-03-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Options',
        ),
    ]
