# Generated by Django 2.1.4 on 2020-03-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0002_auto_20200305_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
