# Generated by Django 3.0.14 on 2021-04-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timezones',
            table=None,
        ),
    ]
