# Generated by Django 3.0.14 on 2021-04-22 06:18

import api.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[(api.enums.TokenType['Reset_Password'], 'Reset Password'), (api.enums.TokenType['Forget_Password'], 'Forget Password'), (api.enums.TokenType['Email_Registration_Confirmation'], 'Email Registration Confirmation')], max_length=100, verbose_name='Token Type')),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Created At')),
                ('expiry_minutes', models.IntegerField(default=30, verbose_name='Expiry Minutes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
