# Generated by Django 3.0.14 on 2021-04-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210409_0947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timezones',
            table='hs_timezones',
        ),
    ]
